### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by rhaamo** [rhaamo/lutrainit#4]
reproduced using lxc:

build with race enabled:
```
2017/06/27 20:02:43 [ INFO] [lutra] Started service network.eth0
==================
WARNING: DATA RACE
Write at 0x00c420148838 by goroutine 13:
  main.Service.Start()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:199 +0x304
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:170 +0x6db

Previous read at 0x00c420148838 by goroutine 16:
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:167 +0x122

Goroutine 13 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:177 +0x5fc

Goroutine 16 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:177 +0x5fc
==================
==================
WARNING: DATA RACE
Write at 0x00c420148840 by goroutine 13:
  main.Service.Start()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:200 +0x3ed
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:170 +0x6db

Previous read at 0x00c420148840 by goroutine 16:
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:170 +0x6ab

Goroutine 13 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:177 +0x5fc

Goroutine 16 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:177 +0x5fc
==================
==================
WARNING: DATA RACE
Write at 0x00c420148838 by goroutine 16:
  main.Service.Start()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:199 +0x304
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:170 +0x6db

Previous read at 0x00c420148838 by goroutine 13:
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:170 +0x6ab

Goroutine 16 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:177 +0x5fc

Goroutine 13 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:177 +0x5fc
==================
File descriptor 25 (anon_inode:[signalfd]) leaked on lvm invocation. Parent PID 192: sh
File descriptor 25 (anon_inode:[signalfd]) leaked on lvm invocation. Parent PID 193: sh
  No volume groups found
  No volume groups found
2017/06/27 20:02:47 [ INFO] [lutra] Started service lvm2
2017/06/27 20:02:47 [ INFO] [lutra] Started service lvm2
2017/06/27 20:02:51 [ INFO] [lutra] Started service mountall
2017/06/27 20:02:51 [TRACE] getty idx 0 tty tty1 autologin root
==================
WARNING: DATA RACE
Write at 0x00c4200736e0 by goroutine 24:
  runtime.mapassign()
      /usr/local/go/src/runtime/hashmap.go:485 +0x0
  main.manageAndSpawnGettys.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:131 +0xb2

Previous write at 0x00c4200736e0 by goroutine 23:
  runtime.mapassign()
      /usr/local/go/src/runtime/hashmap.go:485 +0x0
  main.manageAndSpawnGettys.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:131 +0xb2

Goroutine 24 (running) created at:
  main.manageAndSpawnGettys()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:143 +0x1e0
  main.ManageGettys()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:38 +0x187
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:190 +0x510

Goroutine 23 (running) created at:
  main.manageAndSpawnGettys()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:143 +0x1e0
  main.ManageGettys()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:38 +0x187
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:190 +0x510
==================
2017/06/27 20:02:51 [ INFO] Spawning getty on tty1 with user root
2017/06/27 20:02:51 [TRACE] getty idx 1 tty tty2 autologin
2017/06/27 20:02:51 [ INFO] Spawning getty on tty2 with user
2017/06/27 20:02:51 [TRACE] getty idx 2 tty tty3 autologin
2017/06/27 20:02:51 [TRACE] getty idx 3 tty tty4 autologin
2017/06/27 20:02:51 [ INFO] Spawning getty on tty3 with user
2017/06/27 20:02:51 [ INFO] Spawning getty on tty4 with user
2017/06/27 20:02:51 [TRACE] getty idx 4 tty tty5 autologin
2017/06/27 20:02:51 [ INFO] Spawning getty on tty5 with user
2017/06/27 20:02:51 [TRACE] getty idx 5 tty tty6 autologin
2017/06/27 20:02:51 [ INFO] Spawning getty on tty6 with user
2017/06/27 20:02:51 [TRACE] getty idx 6 tty tty8 autologin
2017/06/27 20:02:51 [ INFO] Spawning getty on tty8 with user
```

raw build:
```
2017/06/27 19:51:45 [ INFO] [lutra] Started service lvm2
2017/06/27 19:51:49 [ INFO] [lutra] Started service mountall
2017/06/27 19:51:49 [TRACE] getty idx 6 tty tty8 autologin
2017/06/27 19:51:49 [ INFO] Spawning getty on tty8 with user
2017/06/27 19:51:49 [TRACE] getty idx 1 tty tty2 autologin
2017/06/27 19:51:49 [ INFO] Spawning getty on tty2 with user
fatal error: concurrent map read and map write

goroutine 37 [running]:
runtime.throw(0x7a4f6a, 0x21)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4200f6ec0 sp=0xc4200f6ea0
runtime.mapaccess1_fast64(0x73c060, 0xc42006b6e0, 0x0, 0x3)
	/usr/local/go/src/runtime/hashmap_fast.go:119 +0x1a8 fp=0xc4200f6ee8 sp=0xc4200f6ec0
main.manageAndSpawnGettys.func1(0xc420152760, 0xc42000f6e0, 0x4, 0x79b544, 0x7, 0x0)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:133 +0x264 fp=0xc4200f6fb0 sp=0xc4200f6ee8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200f6fb8 sp=0xc4200f6fb0
created by main.manageAndSpawnGettys
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:143 +0x3fd

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42015276c)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc420152760)
	/usr/local/go/src/sync/waitgroup.go:131 +0x7a
main.manageAndSpawnGettys()
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:147 +0x42e
main.ManageGettys()
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:38 +0xef
main.main()
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:190 +0x3e6

goroutine 5 [select]:
github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog.init.3.func1()
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog/logger.go:74 +0x15b
created by github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog.init.3
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog/logger.go:81 +0x35

goroutine 7 [semacquire]:
sync.runtime_Semacquire(0xc4201160dc)
	/usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4201160d0)
	/usr/local/go/src/sync/waitgroup.go:131 +0x7a
github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc.(*Server).Serve(0xc420116000, 0x7a475b, 0x20)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc/server.go:177 +0x64
main.socketInitctl()
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/lutractl_sock.go:106 +0x395
created by main.main
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:133 +0x37f

goroutine 17 [select]:
github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc.serverHandler(0xc420116000, 0xc4201061e0)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc/server.go:200 +0x40a
created by github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc.(*Server).Start
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc/server.go:158 +0x370

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7f39a3d56f28, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42011c068, 0x72, 0x0, 0xc420138000)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42011c068, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42011c000, 0x0, 0x912660, 0xc420138000)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*UnixListener).accept(0xc4200f85d0, 0x660c94, 0xc4200ec000, 0x1)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x32
net.(*UnixListener).Accept(0xc4200f85d0, 0x18, 0xc4200227c8, 0x660e22, 0xc42006b770)
	/usr/local/go/src/net/unixsock.go:237 +0x49
github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc.(*netListener).Accept(0xc4201083a0, 0x20002, 0xc4200227c4, 0xc4200227c0, 0xc420022740, 0xc420064480, 0x660dfe)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc/transport.go:118 +0x38
github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc.serverHandler.func1(0xc4200eca50, 0xc4200eca60, 0xc4200eca70, 0xc420116000, 0xc4200eca80, 0xc420106240)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc/server.go:192 +0x3b
created by github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc.serverHandler
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/valyala/gorpc/server.go:198 +0x192

goroutine 34 [runnable]:
github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog.(*console).Start(0xc420142d20)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog/console.go:84 +0x1be
created by github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog.New
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog/logger.go:121 +0x17b

goroutine 36 [syscall]:
syscall.Syscall6(0x3d, 0xffffffffffffffff, 0xc4201b2774, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.wait4(0xffffffffffffffff, 0xc4201b2774, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:172 +0x88
syscall.Wait4(0xffffffffffffffff, 0xc4201b27c4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_linux.go:256 +0x51
main.reapChildren()
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/zombie.go:22 +0x9b
created by main.main
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:188 +0x3e1

goroutine 35 [runnable]:
github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog.(*file).Start(0xc420078700)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog/file.go:286 +0x1be
created by github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog.New
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/vendor/github.com/go-clog/clog/logger.go:121 +0x17b

goroutine 38 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0xc2, 0xc42018fbb8, 0x1000004, 0x0, 0x0, 0x0, 0x60, 0xc4201a00c0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420194330, 0xc4201a00c0, 0x0, 0x3)
	/usr/local/go/src/os/wait_waitid.go:28 +0xa5
os.(*Process).wait(0xc420194330, 0xc4201981f0, 0x0, 0xc4201942d0)
	/usr/local/go/src/os/exec_unix.go:22 +0x4d
os.(*Process).Wait(0xc420194330, 0x0, 0x0, 0x7aee00)
	/usr/local/go/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc4201962c0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:435 +0x62
main.spawnGetty(0x0, 0x0, 0x79aa3d, 0x4, 0xc420194210, 0x0, 0x0)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:178 +0x418
main.manageAndSpawnGettys.func1(0xc420152760, 0x0, 0x0, 0x79aa3d, 0x4, 0x1)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:133 +0x2a9
created by main.manageAndSpawnGettys
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:143 +0x3fd

goroutine 39 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0xc3, 0xc420038bb8, 0x1000004, 0x0, 0x0, 0x0, 0x60, 0xc4201de000)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc4201dc000, 0xc4201de000, 0x0, 0x3)
	/usr/local/go/src/os/wait_waitid.go:28 +0xa5
os.(*Process).wait(0xc4201dc000, 0xc420053000, 0x0, 0xc420143200)
	/usr/local/go/src/os/exec_unix.go:22 +0x4d
os.(*Process).Wait(0xc4201dc000, 0x0, 0x0, 0x7aee00)
	/usr/local/go/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc42007b1e0, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:435 +0x62
main.spawnGetty(0x0, 0x0, 0x79aa41, 0x4, 0xc420143140, 0x0, 0x0)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:178 +0x418
main.manageAndSpawnGettys.func1(0xc420152760, 0x0, 0x0, 0x79aa41, 0x4, 0x2)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:133 +0x2a9
created by main.manageAndSpawnGettys
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:143 +0x3fd

goroutine 40 [runnable]:
main.manageAndSpawnGettys.func1(0xc420152760, 0x0, 0x0, 0x79aa45, 0x4, 0x3)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:132 +0x1b5
created by main.manageAndSpawnGettys
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:143 +0x3fd

goroutine 41 [semacquire]:
sync.runtime_SemacquireMutex(0x95ff64)
	/usr/local/go/src/runtime/sema.go:62 +0x34
sync.(*Mutex).Lock(0x95ff60)
	/usr/local/go/src/sync/mutex.go:87 +0x9d
sync.(*RWMutex).Lock(0x95ff60)
	/usr/local/go/src/sync/rwmutex.go:86 +0x2d
syscall.forkExec(0xc4200ecae0, 0xb, 0xc4200f86c0, 0x3, 0x3, 0xc4200f5bb0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/exec_unix.go:185 +0x1fd
syscall.StartProcess(0xc4200ecae0, 0xb, 0xc4200f86c0, 0x3, 0x3, 0xc4200f5bb0, 0x2, 0x4, 0xc4200fa040, 0xc4200f5b80)
	/usr/local/go/src/syscall/exec_unix.go:240 +0x64
os.startProcess(0xc4200ecae0, 0xb, 0xc4200f86c0, 0x3, 0x3, 0xc4200f5d58, 0xc420108540, 0x2, 0x2)
	/usr/local/go/src/os/exec_posix.go:45 +0x1a3
os.StartProcess(0xc4200ecae0, 0xb, 0xc4200f86c0, 0x3, 0x3, 0xc4200f5d58, 0x0, 0x0, 0xc4200ecae0)
	/usr/local/go/src/os/exec.go:94 +0x64
os/exec.(*Cmd).Start(0xc4201c2000, 0xc420118090, 0xc4200f5e58)
	/usr/local/go/src/os/exec/exec.go:359 +0x3d2
main.spawnGetty(0x0, 0x0, 0x79aa49, 0x4, 0xc4200f8600, 0x0, 0x0)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:171 +0x29c
main.manageAndSpawnGettys.func1(0xc420152760, 0x0, 0x0, 0x79aa49, 0x4, 0x4)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:133 +0x2a9
created by main.manageAndSpawnGettys
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:143 +0x3fd

goroutine 42 [runnable]:
sync.runtime_Semrelease(0x95ff64)
	/usr/local/go/src/runtime/sema.go:57 +0x2b
sync.(*Mutex).Unlock(0x95ff60)
	/usr/local/go/src/sync/mutex.go:126 +0x81
sync.(*RWMutex).Unlock(0x95ff60)
	/usr/local/go/src/sync/rwmutex.go:125 +0x84
syscall.forkExec(0xc42011a6b0, 0xb, 0xc42013a570, 0x3, 0x3, 0xc42018abb0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/exec_unix.go:198 +0x39b
syscall.StartProcess(0xc42011a6b0, 0xb, 0xc42013a570, 0x3, 0x3, 0xc42018abb0, 0x2, 0x4, 0xc420120140, 0xc42018ab80)
	/usr/local/go/src/syscall/exec_unix.go:240 +0x64
os.startProcess(0xc42011a6b0, 0xb, 0xc42013a570, 0x3, 0x3, 0xc42018ad58, 0xc420138480, 0x2, 0x2)
	/usr/local/go/src/os/exec_posix.go:45 +0x1a3
os.StartProcess(0xc42011a6b0, 0xb, 0xc42013a570, 0x3, 0x3, 0xc42018ad58, 0x0, 0x0, 0xc42011a6b0)
	/usr/local/go/src/os/exec.go:94 +0x64
os/exec.(*Cmd).Start(0xc42016e2c0, 0xc4201223f0, 0xc42018ae58)
	/usr/local/go/src/os/exec/exec.go:359 +0x3d2
main.spawnGetty(0x0, 0x0, 0x79aa4d, 0x4, 0xc42013a4b0, 0x0, 0x0)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:171 +0x29c
main.manageAndSpawnGettys.func1(0xc420152760, 0x0, 0x0, 0x79aa4d, 0x4, 0x5)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:133 +0x2a9
created by main.manageAndSpawnGettys
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:143 +0x3fd

goroutine 43 [runnable]:
sync.runtime_SemacquireMutex(0x95ff64)
	/usr/local/go/src/runtime/sema.go:62 +0x34
sync.(*Mutex).Lock(0x95ff60)
	/usr/local/go/src/sync/mutex.go:87 +0x9d
sync.(*RWMutex).Lock(0x95ff60)
	/usr/local/go/src/sync/rwmutex.go:86 +0x2d
syscall.forkExec(0xc4201527d0, 0xb, 0xc420142f60, 0x3, 0x3, 0xc4200f0bb0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/exec_unix.go:185 +0x1fd
syscall.StartProcess(0xc4201527d0, 0xb, 0xc420142f60, 0x3, 0x3, 0xc4200f0bb0, 0x2, 0x4, 0xc420046040, 0xc4200f0b80)
	/usr/local/go/src/syscall/exec_unix.go:240 +0x64
os.startProcess(0xc4201527d0, 0xb, 0xc420142f60, 0x3, 0x3, 0xc4200f0d58, 0xc420148f20, 0x2, 0x2)
	/usr/local/go/src/os/exec_posix.go:45 +0x1a3
os.StartProcess(0xc4201527d0, 0xb, 0xc420142f60, 0x3, 0x3, 0xc4200f0d58, 0x0, 0x0, 0xc4201527d0)
	/usr/local/go/src/os/exec.go:94 +0x64
os/exec.(*Cmd).Start(0xc42007b080, 0xc4200dee10, 0xc4200f0e58)
	/usr/local/go/src/os/exec/exec.go:359 +0x3d2
main.spawnGetty(0x0, 0x0, 0x79aa51, 0x4, 0xc420142ea0, 0x0, 0x0)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:171 +0x29c
main.manageAndSpawnGettys.func1(0xc420152760, 0x0, 0x0, 0x79aa51, 0x4, 0x6)
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:133 +0x2a9
created by main.manageAndSpawnGettys
	/Users/dashie/dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:143 +0x3fd
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --logpriority options.
root@luna:/var/lib/lxc/j-dev-lutrainit#
```

**Comment by rhaamo** [comment]
newer trace after some mutexing:
```
==================
WARNING: DATA RACE
Write at 0x00c420144838 by goroutine 19:
  main.Service.Start()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:202 +0x33e
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:170 +0x6db

Previous read at 0x00c420144838 by goroutine 17:
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:163 +0x7d

Goroutine 19 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:179 +0x5fc

Goroutine 17 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:179 +0x5fc
==================
==================
WARNING: DATA RACE
Write at 0x00c420144840 by goroutine 19:
  main.Service.Start()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:203 +0x427
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:170 +0x6db

Previous read at 0x00c420144840 by goroutine 17:
  main.StartServices.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:163 +0x7d

Goroutine 19 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:179 +0x5fc

Goroutine 17 (running) created at:
  main.StartServices()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/service.go:187 +0x299
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:179 +0x5fc
==================
File descriptor 25 (anon_inode:[signalfd]) leaked on lvm invocation. Parent PID 190: sh
  No volume groups found
2017/06/27 21:46:06 [ INFO] [lutra] Started service lvm2
2017/06/27 21:46:10 [ INFO] [lutra] Started service mountall
2017/06/27 21:46:10 [TRACE] getty idx 0 tty tty1 autologin root
==================
WARNING: DATA RACE
Write at 0x00c4200756e0 by goroutine 24:
  runtime.mapassign()
      /usr/local/go/src/runtime/hashmap.go:485 +0x0
  main.manageAndSpawnGettys.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:134 +0xb2

Previous write at 0x00c4200756e0 by goroutine 23:
  runtime.mapassign()
      /usr/local/go/src/runtime/hashmap.go:485 +0x0
  main.manageAndSpawnGettys.func1()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:134 +0xb2

Goroutine 24 (running) created at:
  main.manageAndSpawnGettys()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:146 +0x1e0
  main.ManageGettys()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:41 +0x1a7
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:192 +0x510

Goroutine 23 (running) created at:
  main.manageAndSpawnGettys()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:146 +0x1e0
  main.ManageGettys()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/getty.go:41 +0x1a7
  main.main()
      /media/sf_dev/go/src/github.com/rhaamo/lutrainit/lutrainit/main.go:192 +0x510
==================
```
